# -*- coding: utf-8 -*-
"""DL_LAB3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F4Gfk1u0ckquaU6qXEwK-FfUQougaNa5
"""

import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

from google.colab import drive

drive.mount('/content/drive')

!find /content/drive/MyDrive -name "archive.zip"

import zipfile

zip_path = "/content/drive/MyDrive/DL_Lab/archive.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall("/content")

print("ZIP extracted successfully!")

!find /content -maxdepth 3 -type d

import os

DATASET_PATH = "/content/data"

classes = [
    "Blight",
    "Common_Rust",
    "Gray_Leaf_Spot",
    "Healthy"
]

for c in classes:
    folder = os.path.join(DATASET_PATH, c)
    files = [
        f for f in os.listdir(folder)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]
    print(f"{c}: {len(files)}")

import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

import os
import random
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support
)

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

DATASET_PATH = "/content/data"

IMG_HEIGHT = 224
IMG_WIDTH = 224

BATCH_SIZE = 32
EPOCHS = 20
LEARNING_RATE = 0.001

CLASS_NAMES = [
    "Blight",
    "Common_Rust",
    "Gray_Leaf_Spot",
    "Healthy"
]

NUM_CLASSES = len(CLASS_NAMES)

for file_name in os.listdir(class_folder):
  VALID_EXTENSIONS = (
    ".jpg",
    ".jpeg",
    ".png",
    ".JPG",
    ".JPEG",
    ".PNG"
)

image_paths = []
labels = []

for label, class_name in enumerate(CLASS_NAMES):

    class_folder = os.path.join(
        DATASET_PATH,
        class_name
    )

    if not os.path.exists(class_folder):
        print(f"Folder not found: {class_folder}")
        continue

    for file_name in os.listdir(class_folder):

        if file_name.endswith(VALID_EXTENSIONS):

            image_path = os.path.join(
                class_folder,
                file_name
            )

            image_paths.append(image_path)
            labels.append(label)

image_paths = np.array(image_paths)
labels = np.array(labels)

print("Total images:", len(image_paths))

print("\n===================================")
print("DATASET INFORMATION")
print("===================================")

print("Total Images:", len(image_paths))

print("\nImages per class:")

for i, class_name in enumerate(CLASS_NAMES):
    count = np.sum(labels == i)
    print(f"{class_name}: {count}")

X_train, X_temp, y_train, y_temp = train_test_split(
    image_paths,
    labels,
    test_size=0.30,
    random_state=SEED,
    stratify=labels
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=SEED,
    stratify=y_temp
)

print("\n===================================")
print("DATASET SPLIT")
print("===================================")

print("Training Images  :", len(X_train))
print("Validation Images:", len(X_val))
print("Testing Images   :", len(X_test))

def load_image(image_path, label):

    image = tf.io.read_file(image_path)

    image = tf.image.decode_image(
        image,
        channels=3,
        expand_animations=False
    )

    image.set_shape([None, None, 3])

    image = tf.image.resize(
        image,
        (IMG_HEIGHT, IMG_WIDTH)
    )

    image = tf.cast(
        image,
        tf.float32
    )

    return image, label

AUTOTUNE = tf.data.AUTOTUNE

# TRAINING DATA
train_ds = tf.data.Dataset.from_tensor_slices(
    (X_train, y_train)
)

train_ds = train_ds.map(
    load_image,
    num_parallel_calls=AUTOTUNE
)

train_ds = train_ds.shuffle(
    buffer_size=len(X_train),
    seed=SEED
)

train_ds = train_ds.batch(BATCH_SIZE)
train_ds = train_ds.prefetch(AUTOTUNE)


# VALIDATION DATA
val_ds = tf.data.Dataset.from_tensor_slices(
    (X_val, y_val)
)

val_ds = val_ds.map(
    load_image,
    num_parallel_calls=AUTOTUNE
)

val_ds = val_ds.batch(BATCH_SIZE)
val_ds = val_ds.prefetch(AUTOTUNE)


# TEST DATA
test_ds = tf.data.Dataset.from_tensor_slices(
    (X_test, y_test)
)

test_ds = test_ds.map(
    load_image,
    num_parallel_calls=AUTOTUNE
)

test_ds = test_ds.batch(BATCH_SIZE)
test_ds = test_ds.prefetch(AUTOTUNE)

print("TensorFlow datasets created successfully!")

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.RandomContrast(0.1)
])

print("Data augmentation created!")

cnn_model = models.Sequential([

    layers.Input(
        shape=(IMG_HEIGHT, IMG_WIDTH, 3)
    ),

    # Data Augmentation
    data_augmentation,

    # Normalize pixels from 0-255 to 0-1
    layers.Rescaling(1.0 / 255),

    # =========================
    # CNN BLOCK 1
    # =========================

    layers.Conv2D(
        32, (3, 3),
        activation="relu",
        padding="same"
    ),

    layers.BatchNormalization(),

    layers.Conv2D(
        32, (3, 3),
        activation="relu",
        padding="same"
    ),

    layers.MaxPooling2D((2, 2)),

    # =========================
    # CNN BLOCK 2
    # =========================

    layers.Conv2D(
        64, (3, 3),
        activation="relu",
        padding="same"
    ),

    layers.BatchNormalization(),

    layers.Conv2D(
        64, (3, 3),
        activation="relu",
        padding="same"
    ),

    layers.MaxPooling2D((2, 2)),

    # =========================
    # CNN BLOCK 3
    # =========================

    layers.Conv2D(
        128, (3, 3),
        activation="relu",
        padding="same"
    ),

    layers.BatchNormalization(),

    layers.Conv2D(
        128, (3, 3),
        activation="relu",
        padding="same"
    ),

    layers.MaxPooling2D((2, 2)),

    # =========================
    # CNN BLOCK 4
    # =========================

    layers.Conv2D(
        256, (3, 3),
        activation="relu",
        padding="same"
    ),

    layers.BatchNormalization(),

    layers.Conv2D(
        256, (3, 3),
        activation="relu",
        padding="same"
    ),

    layers.MaxPooling2D((2, 2)),

    # =========================
    # CLASSIFICATION
    # =========================

    layers.GlobalAveragePooling2D(),

    layers.Dense(
        256,
        activation="relu"
    ),

    layers.Dropout(0.5),

    layers.Dense(
        128,
        activation="relu"
    ),

    layers.Dropout(0.3),

    # Output: 4 classes
    layers.Dense(
        NUM_CLASSES,
        activation="softmax"
    )
])

print("CNN model created successfully!")

cnn_model.summary()

cnn_model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=LEARNING_RATE
    ),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("Model compiled successfully!")

callbacks = [

    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    ),

    tf.keras.callbacks.ModelCheckpoint(
        "best_deep_cnn_model.keras",
        monitor="val_accuracy",
        save_best_only=True,
        verbose=1
    ),

    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        min_lr=0.000001,
        verbose=1
    )
]

print("Callbacks created successfully!")

print("\n===================================")
print("TRAINING DEEP CNN MODEL")
print("===================================\n")

history = cnn_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=callbacks,
    verbose=1
)

print("\n===================================")
print("TESTING DEEP CNN MODEL")
print("===================================\n")

test_loss, test_accuracy = cnn_model.evaluate(
    test_ds,
    verbose=1
)

print("\n===================================")
print("FINAL RESULTS")
print("===================================")

print(f"Test Loss     : {test_loss:.4f}")
print(f"Test Accuracy : {test_accuracy * 100:.2f}%")

predictions = cnn_model.predict(test_ds)

y_pred = np.argmax(
    predictions,
    axis=1
)

print("Predictions completed!")

print("\n===================================")
print("CLASSIFICATION REPORT")
print("===================================\n")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=CLASS_NAMES,
        digits=4,
        zero_division=0
    )
)

precision, recall, f1_score, _ = precision_recall_fscore_support(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)

print("\n===================================")
print("PERFORMANCE METRICS")
print("===================================")

print(f"Accuracy  : {test_accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-Score  : {f1_score:.4f}")

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\n===================================")
print("CONFUSION MATRIX")
print("===================================\n")

print(cm)

plt.figure(figsize=(8, 6))

plt.imshow(cm)

plt.title("Deep CNN Confusion Matrix")
plt.colorbar()

tick_marks = np.arange(NUM_CLASSES)

plt.xticks(
    tick_marks,
    CLASS_NAMES,
    rotation=45
)

plt.yticks(
    tick_marks,
    CLASS_NAMES
)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(
            j,
            i,
            str(cm[i, j]),
            ha="center",
            va="center"
        )

plt.xlabel("Predicted Class")
plt.ylabel("Actual Class")

plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))

plt.plot(
    history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.title("Deep CNN Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.legend()
plt.grid()

plt.show()

plt.figure(figsize=(8, 5))

plt.plot(
    history.history["loss"],
    label="Training Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.title("Deep CNN Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.legend()
plt.grid()

plt.show()

cnn_model.save(
    "/content/final_deep_cnn_maize_model.keras"
)

print("\n===================================")
print("DEEP CNN COMPLETED SUCCESSFULLY")
print("===================================")

print("\nSaved model:")
print("/content/final_deep_cnn_maize_model.keras")